### ISSUE TITLE
Formatted text

### ISSUE THREAD

**Issue by davidoskky** [fossar/selfoss#1220]
Using fulltextrss the full html of the article should be recovered.
Would it be possible to maintain the formatting of the original text?
What I would like is to have italic and bold sections as such in selfoss. Sometimes in articles the presence of a sentence in italic or a bold word may translate in a significant difference in the meaning.

**Comment by jtojnar** [comment]
I would expect the formatting to be preserved, unless it is done in CSS, which might be hard. Do you have an example of site where such formatting occurs?

**Comment by davidoskky** [comment]
I did not find a recent one in english...
https://ilblogdellasci.wordpress.com/feed/
In the last article (21/09/2020) there is a large paragraph in italic, this is not shown inside selfoss.

**Comment by jtojnar** [comment]
Hmm, looks like the css reset we use is eating the style for `<em>`. For now, you can put the following into `user.css` in your selfoss directory:


```css
.entry-content i, .entry-content em {
    font-style: italic;
}

.entry-content b, .entry-content strong {
    font-weight: bold;
}
```
