### ISSUE TITLE
Feature request: Disable/hide offline mode

### ISSUE THREAD

**Issue by gerundt** [fossar/selfoss#1393]
Since I don't need/use the Offline Mode it would be cool to disable/hide the whole feature. Maybe with an option?

This would help to hide the check box from the login screen. 🤣

**Comment by jtojnar** [comment]
You can put the following into `user.css` at the root of your selfoss tree:

```css
#login label[for="enableoffline"], #login label[for="enableoffline"] + label {
	display: none;
}
```
